### ISSUE TITLE
Allow port to be specified as a command line argument

### ISSUE THREAD

**Issue by ryanguill** [tapio/live-server#10]
Would you be interested in a PR to accept the port to use on the command line? I use tomcat for other things (which uses 8080 by default) and setting an environment variable as generic as PORT isn't really an option for me either.

**Comment by tapio** [comment]
Yes, I'd be interested in that. I used an env var because I wanted to keep things simple and not bother with parsing command line until really needed.

Note though that as a work-around you don't need to set a global env var if you either make a shell alias or put into a wrapper script the line `PORT=3000 live-server` (which will only set/change the var for that process instance).

**Comment by ryanguill** [comment]
unfortunately the PORT=8181 live-server doesn't seem to work on windows.  A batch file would be a decent workaround in the meantime for me though, I didn't really consider that.  I will still probably submit a PR though eventually.

**Comment by Pomax** [comment]
+1, being able to run `live-server --port=1234`, with live-server checking for a port flag first, then the process.env, would be infinitely more useful. Not just on Windows but also on systems that need to kick off multiple live-servers programmatically. Constantly rebinding the PORT instead of passing a dedicated value is likely to lead to vvery interesting inconsistencies.

**Comment by Pomax** [comment]
filed a PR to add this capability to live-server
