### ISSUE TITLE
different from live-reload or browsersync?

### ISSUE THREAD

**Issue by amcdnl** [tapio/live-server#100]
How is this different from live-reload or browsersync? would be helpful to doc that in the readme.

**Comment by paulcpederson** [comment]
@amcdnl different in a couple ways as far as I can tell from quickly looking at the different projects. It's different than browsersync in that it isn't **ridiculously huge**. browser-sync has about 252 dependencies in its tree, and requires you to compile fsevents, bufferutil, and utf-8-validate.

It is different from live-reload in that for live-reload you need to add a browser extension or a snippet of code to your html pages, which you don't need to in live-server.

**Comment by amcdnl** [comment]
I kinda thought that was it, you should add a note in the readme.

Any plans to support http2? what about middlewares?

**Comment by tapio** [comment]
Live server has been fulfilling my personal requirements for years now, so I don't have many plans for it. I merge in features other people contribute, but at the same time I'm trying to avoid feature creep and bloat. Not sure how well I'm doing in that regard these days since there are already more than a dozen options, but at least the code is still at a manageable size at about 300 lines excluding command line handling and tests.
