### ISSUE TITLE
Serve from a base url

### ISSUE THREAD

**Issue by ludohenin** [tapio/live-server#37]
It would be nice (unless I missed something) to be able to serve files from a base url.
I'm working with a remote server and I'm targeting for example `my-domain.com/base` (proxied to my live-server) but I'm (obviously) getting `Cannot GET /base`.

**Comment by harrytruong** [comment]
Not sure what you're looking for, but would it be possible to just create a `/base` folder, and have `live-server` running from one directory higher? It would be the simplest fix. 

Otherwise, when you say "serve from base url" do you mean like:

 1. With this example file structure:

  ```
  root
  |-- foo
  |    |-- apple
  |-- bar
  |    |-- banana
  |    |-- orange
  ```

 2. And running `live-server` from root:

  ```bash
  $ live-server --base=alias
  ```

 3. Should results in requests matching:
  + `GET /foo/apple` = `404 Not Found`
  + `GET /alias/foo/apple` = `200` loading `foo/apple`
  + `GET /alias/bar/banana` = `200` loading `bar/banana`
  + `GET /bar/banana` = `404 Not Found`

**Comment by ludohenin** [comment]
@harrytruong this is exactly it.

**Comment by tapio** [comment]
WIP at branch [base-url](https://github.com/tapio/live-server/tree/base-url).

**Comment by ludohenin** [comment]
Looks good. I think you can merge that one.

**Comment by heminm** [comment]
Please merge. This would be a great feature.

**Comment by tapio** [comment]
Master now has a new option `--mount=ROUTE:PATH - serve the paths contents under the defined route (multiple definitions possible)` which should be useful for this use case also.

**Comment by tapio** [comment]
I'm going to close this now, but feel free to reopen/complain if `--mount=ROUTE:PATH` param does not do it for you.

**Comment by efc** [comment]
I am confused about how the `--mount` option actually resolves the request for a `--base` option. The `--base` option would apply to the whole site universally. Can someone describe how to use the `--mount` option to do the same? I don't see any documentation of acceptable routes or how to create a wildcard route that applies to the whole site. 

BTW, I opened [another issue](https://github.com/tapio/live-server/issues/287) about this before realizing that this one could be reopened. Apologies for not knowing what is the correct process.
