### ISSUE TITLE
eslint

### ISSUE THREAD

**Issue by richardgoater** [tapio/live-server#41]
I'd like to suggest that the codebase be made more consistent through the use of [eslint](http://eslint.org/). If you agree, I'd like to volunteer to do the cleaning, please suggest the ruleset you'd like to use and I can get to work.

I would suggest switching from tabs to spaces for better-looking diffs but it's completely up to you :)

**Comment by tapio** [comment]
I've added some eslint rules. Currently, `npm test` runs both jshint and eslint. I'm probably not going to follow them to the letter though, because some things are not so clear-cut: For example, unused variables are generally bad and I would like to catch them, but then again I'd like to keep them in callback parameters as it makes clearer what the full signature is, and what is available etc.
