### ISSUE TITLE
gzip files

### ISSUE THREAD

**Issue by daniele-zurico** [tapio/live-server#86]
Hi guys,
sorry for the newbie question. There's any way to tell to live-server to enable the gzip-compression.
I've create 2 build files one normal and one gzip and I would to load the second one.
thanks,
Daniele

**Comment by naivefun** [comment]
+1

**Comment by pavel** [comment]
Why do you think this is useful with `live-server`?
`live-server` is supposed to be
> a little development server with live reload capability.
Not sure why you need gzip for development server.
Can you explain?

**Comment by naivefun** [comment]
@pavel  The idea is very easy to view zipped size from browser inspector compared to the original. Just for convenience.

**Comment by yqrashawn** [comment]
@pavel I'm using 3d data for my data visualizer. And those data are gziped. I believed there're developers like me testing there project with gziped data.

**Comment by MrRobboto** [comment]
I'll second this request - using live-server in an Aurelia, Typescript, System environment and have source files loaded individually, and vendor code bundled up and gzipped.  This feature would take my biggest file, the bundle from ~2MB to ~500KB so this would be great in development.

**Comment by t-p-l-k** [comment]
Useful feature, I'd like to see it too.

**Comment by MrRobboto** [comment]
^Yeah, certainly the premise that you wouldn't want compression in development is flaud.  Plenty of people have bundles or something similar that they barely ever change in development - why not gzip them and see your code changes faster in development?  Well that's what I do because I don't like waiting for my browser to load 300 files and 8MB everytime I change code so I bundle and compress all the stuff I'm not working on.  I've been using http-server (another light server but with gzip, because it makes sense) with gulp live-reload and the live-reload chrome extension (have to turn it on every code session).  Not ideal but allows live-reload with gzip!

**Comment by falkben** [comment]
I think useful to me would be serving gzip or brotli compressed files, when they exist, when requests come for a file without an extension, similar to how http-server does.
